#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent


# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"

# Load erpnext-modules.env file

erp_next_modules = "erpnext-modules.env"

if os.path.exists(erp_next_modules):
    with open(erp_next_modules, "r") as f:
        for line in f:
            key, value = line.strip().split("=")
            if key in config:
                if key == "ERP_NEXT_MODULES":
                    try:
                        config[key] = json.loads(value)
                    except json.JSONDecodeError:
                        print(f"Error decoding JSON for key {key}. Using default value.")
                else:
                    config[key] = value

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
