#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent


# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST", "")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"
# Load erpnext-modules.env file
if os.path.exists("erpnext-modules.env"):
    data = agent.read_envfile("erpnext-modules.env")
    config["erpSelectedModules"] = data.get("ERP_NEXT_MODULES", [])
    config["appJson"] = data.get("APPS_JSON")
else:
    config["erpSelectedModules"] = []

if os.path.exists("backup_paths.env"):
    data = agent.read_envfile("backup_paths.env")
    config["hasBackup"] = True


# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
