#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent


# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST", "")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"
# Load erpnext-modules.env file
if os.path.exists("erpnext-modules.env"):
    data = agent.read_envfile("erpnext-modules.env")
    modules_str = data.get("ERP_NEXT_MODULES", "")
    config["erpSelectedModules"] = modules_str.split(",") if modules_str else []
    config["appJson"] = data.get("APPS_JSON", "")
    config["frappeVersion"] = data.get("FRAPPE_VERSION", "version-15")
else:
    config["erpSelectedModules"] = []
    config["appJson"] = ""
    config["frappeVersion"] = "version-15"

if os.path.exists("backup_paths.env"):
    data = agent.read_envfile("backup_paths.env")
    config["hasBackup"] = True
else:
    config["hasBackup"] = False

cache_file = ".app_json_cache"
if os.path.exists(cache_file):
    try:
        with open(cache_file) as f:
            cache_data = json.load(f)
        config["builtVersion"] = cache_data.get("version", "")
        config["builtImage"] = cache_data.get("image", "")
        config["builtAt"] = cache_data.get("built_at", "")
    except (json.JSONDecodeError, IOError):
        config["builtVersion"] = ""
        config["builtImage"] = ""
        config["builtAt"] = ""
else:
    config["builtVersion"] = ""
    config["builtImage"] = ""
    config["builtAt"] = ""


# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
