#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# This is specific to you module, so you need to change it accordingly.

ERP_NEXT_MODULES = data.get("erpSelectedModules", [])
APP_JSON = data.get("appJson")
FRAPPE_VERSION = data.get("frappeVersion", "version-15")
FORCE_REBUILD = data.get("forceRebuild", False)

agent.write_envfile(
    "erpnext-modules.env", {"ERP_NEXT_MODULES": ",".join(ERP_NEXT_MODULES) if ERP_NEXT_MODULES else "", "APPS_JSON": APP_JSON, "FRAPPE_VERSION": FRAPPE_VERSION, "FORCE_REBUILD": str(FORCE_REBUILD).lower()}
)

agent.dump_env()
